### ISSUE TITLE
lua_call is not found

### ISSUE THREAD

**Issue by davidsdearaujo** [au-top/dart_lua_ffi#2]
Why there isn't the [lua_call](https://www.lua.org/manual/5.4/manual.html#lua_call) method?

**Comment by au-top** [comment]
> Why there isn't the [lua_call](https://www.lua.org/manual/5.4/manual.html#lua_call) method?

hi ! 
look at https://github.com/au-top/dart_lua_ffi/blob/da70638c10099ddf444f37e31768fdd9dcc3f34e/c_header/lua.h  in  283 line
```c
LUA_API void  (lua_callk) (lua_State *L, int nargs, int nresults,
                           lua_KContext ctx, lua_KFunction k);
#define lua_call(L,n,r)		lua_callk(L, (n), (r), 0, NULL)
```

function `lua_call(L,n,r)` api  is `lua_callk(L, (n), (r), 0, NULL)`

**Comment by davidsdearaujo** [comment]
Thank you!
